require 'json'
default_platform(:ios)

platform :ios do
  desc "Upload ONLY metadata and promotional text (no build, no screenshots)"
  lane :metadata do
    api_key = app_store_connect_api_key(
      key_id: "3GB6K78M56",
      issuer_id: "69a6de81-d2b1-47e3-e053-5b8c7c11a4d1",
      key_filepath: "AuthKey_3GB6K78M56.p8",
      in_house: false
    )
    deliver(
      api_key: api_key,
      app_identifier: "app.chefs.my-chess-board",
      app_version: "1.0",
      app_review_information: JSON.parse(File.read("metadata/review_information.json")),
      skip_screenshots: true,
      skip_binary_upload: true,
      submit_for_review: false,
      force: true
    )
  end
end
