default_platform(:ios)

platform :ios do
  desc "Upload ONLY metadata and promotional text (no build, no screenshots)"
  lane :metadata do
    deliver(
      skip_screenshots: true,
      skip_binary_upload: true,
      submit_for_review: false
    )
  end
end